#!/bin/sh -eux

ub_install

# fool packages looking to link to non-wide-character ncurses libraries
for lib in ncurses ncurses++ form menu panel; do
    echo "INPUT(-l${lib}w)" > "$UB_INSTALLDIR/usr/lib/lib${lib}.so"
    ln -s ${lib}w.pc "$UB_INSTALLDIR/usr/lib/pkgconfig/${lib}.pc"
done

chmod 755 "$UB_INSTALLDIR"/usr/lib/lib*.so.*
