#!/bin/sh -eux

cp zip "$UB_INSTALLDIR"/usr/bin/
cp zipcloak "$UB_INSTALLDIR"/usr/bin/
cp zipnote "$UB_INSTALLDIR"/usr/bin/
cp zipsplit "$UB_INSTALLDIR"/usr/bin/
cp man/zip.1 "$UB_INSTALLDIR"/usr/share/man/man1/
