#!/bin/sh -eux

cd "$UB_OBJECTDIR"

touch "$UB_INSTALLDIR"/etc/ld.so.conf
make \
	install_root="$UB_INSTALLDIR" \
	install
make \
	install_root="$UB_INSTALLDIR" \
	localedata/install-locales

mv "$UB_INSTALLDIR"/sbin/{ldconfig,sln} "$UB_INSTALLDIR"/usr/sbin
rm -rf "$UB_INSTALLDIR"/sbin

cp -p "$UB_COMPILEDIR"/nss/nsswitch.conf "$UB_INSTALLDIR"/etc/
cp -p "$UB_COMPILEDIR"/posix/gai.conf    "$UB_INSTALLDIR"/etc/

rm -f "$UB_INSTALLDIR"/etc/ld.so.cache
rm -f "$UB_INSTALLDIR"/usr/libexec/pt_chown

# compat symlink
# ln -s usr/lib "$UB_INSTALLDIR"/lib64

# force using libxcrypt in other codes
rm -f "$UB_INSTALLDIR"/usr/include/crypt.h
rm -f "$UB_INSTALLDIR"/usr/lib/libcrypt.{a,so}
