#!/bin/sh -eux

sed -i 's/x-fluid.desktop/fluid.desktop/' -i fluid/Makefile

ub_compile \
    -DFLTK_BUILD_TEST=OFF \
    -DFLTK_BUILD_EXAMPLES=OFF \
	-DOPTION_BUILD_SHARED_LIBS=ON \
	-DOPTION_CAIRO=ON
