#!/bin/sh -eux

# alapinstalláció
make DESTDIR="${UB_INSTALLDIR}" \
    CUPSSERVERROOT="${UB_INSTALLDIR}$(cups-config --serverroot)" \
    CUPSSERVERBIN="${UB_INSTALLDIR}$(cups-config --serverbin)" \
    soinstall

# elegendő egy szimlink
ln -s gsc "${UB_INSTALLDIR}"/usr/bin/gs

# remove useless broken doc/ symlink - FS#59507
rm -f "${UB_INSTALLDIR}"/usr/share/ghostscript/${UB_VERSION}/doc

# tools
mkdir -p ${UB_INSTALLDIR}/usr/share/ghostpcl
cp -pr {xps,pcl}/'tools' "${UB_INSTALLDIR}/usr/share/ghostpcl/"
cp -pr 'pcl/urwfonts' "${UB_INSTALLDIR}/usr/share/ghostpcl/"

# ghostxsp rész
cp sobin/gxpsc "${UB_INSTALLDIR}"/usr/bin/
ln -s gxpsc "${UB_INSTALLDIR}"/usr/bin/gxps
cp sobin/libgxps.so.${UB_VERSION_HEAD2} "${UB_INSTALLDIR}"/usr/lib/

# ghostpcl rész
cp sobin/gpcl6c "${UB_INSTALLDIR}"/usr/bin/
ln -s gpcl6c "${UB_INSTALLDIR}"/usr/bin/gpcl6
ln -s gpcl6 "${UB_INSTALLDIR}"/usr/bin/pcl6
ln -s "${UB_INSTALLDIR}"/usr/share/ghostpcl/tools/pcl2pdf "${UB_INSTALLDIR}"/usr/bin/pcl2pdf
ln -s "${UB_INSTALLDIR}"/usr/share/ghostpcl/tools/pcl2pdfwr "${UB_INSTALLDIR}"/usr/bin/pcl2pdfwr
cp sobin/libgpcl6.so.${UB_VERSION_HEAD2} "${UB_INSTALLDIR}"/usr/lib/

# ijs
cd ijs
ub_install
