#!/bin/sh -eux

scdoc < extra/man/alacritty.1.scd > extra/man/alacritty.1
scdoc < extra/man/alacritty.5.scd > extra/man/alacritty.5

mkdir -p ${UB_INSTALLDIR}/usr/share/{applications,appdata,doc/alacritty/example,bash-completion/completions,fish/completions,pixmaps}
cp target/release/alacritty ${UB_INSTALLDIR}/usr/bin/alacritty.bin
cp extra/man/alacritty.1 ${UB_INSTALLDIR}/usr/share/man/man1/alacritty.1
cp extra/man/alacritty.5 ${UB_INSTALLDIR}/usr/share/man/man1/alacritty.5
cp extra/linux/Alacritty.desktop ${UB_INSTALLDIR}/usr/share/applications/
cp extra/linux/org.alacritty.Alacritty.appdata.xml ${UB_INSTALLDIR}/usr/share/appdata/org.alacritty.Alacritty.appdata.xml
cp extra/logo/alacritty-term.svg ${UB_INSTALLDIR}/usr/share/pixmaps/Alacritty.svg
cp extra/completions/alacritty.bash ${UB_INSTALLDIR}/usr/share/bash-completion/completions/alacritty
cp extra/completions/alacritty.fish ${UB_INSTALLDIR}/usr/share/fish/completions/
