#!/bin/sh -eux

ub_install DESTDIR="$UB_INSTALLDIR"

cd docs/manpages
for i in *; do
	m="${i##*.}"
	cp -a "$i" "$UB_INSTALLDIR"/usr/share/man/man${m}/
done

# usershare
mkdir -p "$UB_INSTALLDIR"/var/lib/samba/usershare
chmod 1770 "$UB_INSTALLDIR"/var/lib/samba/usershare
