#!/bin/sh -eux

aclocal -I config-scripts
autoconf -I config-scripts
export CFLAGS='-fcond-mismatch'
ub_compile \
	--exec_prefix=/usr \
	--libdir=/usr/lib \
	--with-logdir=/var/log/cups \
	--with-docdir=/usr/share/cups/doc \
	--with-rundir=/run/cups \
	--with-cupsd-file-perm=0755 \
    --with-cups-user=4 \
    --with-cups-group=7 \
	--disable-pam \
	--enable-sync_on_close \
	--enable-raw-printing \
	--enable-libpaper \
	--enable-webif \
	--enable-relro
