#!/bin/sh -eux

make \
	BUILDROOT="$UB_INSTALLDIR" \
	install

rm -rf "$UB_INSTALLDIR"/etc/init.d
rm -rf "$UB_INSTALLDIR"/etc/rc*.d
rm -rf "$UB_INSTALLDIR"/etc/xinetd.d
rm -rf "$UB_INSTALLDIR"/run

# create empty config files
touch ${UB_INSTALLDIR}/etc/cups/printers.conf
touch ${UB_INSTALLDIR}/etc/cups/classes.conf
touch ${UB_INSTALLDIR}/etc/cups/subscriptions.conf

# comment out all conversion rules which use any of the removed filters
perl -p -i -e 's:^(.*\s+bannertops\s*)$:#\1:' "$UB_INSTALLDIR"/usr/share/cups/mime/mime.convs
