#!/bin/sh -eux

ub_compile \
    -DBYTECODE_RUNTIME=none \
    -DENABLE_EXTERNAL_MSPACK=ON \
    -DENABLE_MILTER=OFF \
    -DENABLE_TESTS=OFF \
    -DDATABASE_DIRECTORY=/var/lib/clamav \
    -DAPP_CONFIG_DIRECTORY=/etc/clamav
