#!/bin/sh -eux

touch src/revision.txt

./bootstrap
export LUAC=luac5.2
ub_compile \
	--enable-flac \
	--enable-faad \
	--enable-svg \
	--enable-jack \
	--enable-lirc \
	--enable-xcb \
	--enable-nls \
	--enable-sftp \
	--disable-dav1d \
	--disable-opencv \
	--disable-update-check \
    --enable-qt
