#!/bin/sh -eux

export PKG_CONFIG_PATH="/usr/lib/ffmpeg4.4/pkgconfig"
export CXXFLAGS+=" -std=c++17"
touch src/revision.txt

./bootstrap
export LUAC=luac5.2
ub_compile \
	--enable-flac \
	--enable-faad \
	--enable-svg \
	--enable-jack \
	--enable-lirc \
	--enable-xcb \
	--enable-nls \
	--enable-sftp \
	--disable-opencv \
	--disable-update-check \
    --enable-qt
