#!/bin/sh -eux

# patchelf for bootjdk
find bootjdk/bin -type f -exec patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 &> /dev/null {} \;
find bootjdk/lib -type f -exec patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 &> /dev/null {} \;

_CFLAGS=" -O2"
_CXXFLAGS=" -O2"
_LDFLAGS=" -Wl,--as-needed"

bash configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sharedstatedir=/var \
    --with-boot-jdk=./bootjdk \
    --with-version-pre="" \
    --with-version-opt="" \
    --with-stdc++lib=dynamic \
    --with-extra-cflags="${_CFLAGS}" \
    --with-extra-cxxflags="${_CXXFLAGS}" \
    --with-extra-ldflags="${_LDFLAGS}" \
    --with-libjpeg=system \
    --with-giflib=system \
    --with-libpng=system \
    --with-lcms=system \
    --with-zlib=system \
    --with-jvm-features=zgc \
    --enable-unlimited-crypto \
    --enable-ccache \
    --disable-warnings-as-errors \
    --with-num-cores=${UB_MAKE_PROCS}

make images legacy-jre-image
