#!/bin/sh -eux

export PYTHON=/usr/bin/python3
export AUTOMAKE='automake --foreign'
touch NEWS README AUTHORS Changelog
autoreconf -vif

ub_compile \
	--enable-scan-build \
	--enable-gui-build \
	--enable-qt5 \
	--disable-qt4 \
	--enable-hpcups-install \
	--enable-cups-drv-install \
	--disable-imageProcessor-build
