#!/bin/sh -eux

pythonver=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
sitedir=${UB_INSTALLDIR}/usr/lib/python${pythonver}/site-packages
mkdir -p $sitedir
python3 bootstrap_install.py --installdir $sitedir dist/flit_core-*.whl
