#!/bin/sh -eux

ub_compile \
    -Dpython=enabled \
    -Ddevtools=disabled \
    -Dvaapi=disabled \
    -Dsharp=disabled \
    -Dgst-examples=disabled \
    -Drs=disabled \
    -Dlibnice=disabled \
    -Dtls=disabled \
    -Dorc-source=system \
    -Dtests=disabled \
    -Dexamples=disabled
