#!/bin/sh -eux

git clone https://github.com/eranif/ctags.git ctags
git clone https://github.com/eranif/wxdap.git wxdap
git clone https://github.com/jbeder/yaml-cpp.git yaml-cpp
git clone https://github.com/eranif/cc-wrapper.git cc-wrapper
git clone https://github.com/eranif/tinyjson.git cc-wrapper/tinyjson
git clone https://github.com/cubicdaiya/dtl.git dtl

cd wxdap
git checkout 10f57bb
cd ..

cd yaml-cpp
git checkout 1b50109
cd ..

cd cc-wrapper
git checkout 6771344
cd ..

cd cc-wrapper/tinyjson
git checkout a6b0d0d
cd ../..

ub_compile \
    -DCMAKE_INSTALL_LIBDIR=lib
