#!/bin/sh -eux

cd build_unix
CFLAGS=-Wno-error=implicit-function-declaration \
../dist/configure --prefix=/usr \
    --enable-compat185 \
    --enable-shared \
    --disable-static \
    --enable-cxx
make LIBSO_LIBS=-lpthread
