#!/bin/sh -eux

ub_compile \
	-Dudev_dir=/usr/lib/udev/ \
	-Dconfig_dhcp_default=internal \
	-Dsession_tracking=systemd \
	-Difupdown=true \
	-Dmodify_system=true \
	-Dconcheck=true \
	-Dselinux=false \
	-Dnmtui=false \
	-Dqt=false \
	-Dbluez5_dun=true \
	-Dpolkit=true
