#!/bin/sh -eux

ub_compile \
	-Dudev_dir=/usr/lib/udev/ \
	-Dkernel_firmware_dir=/usr/lib/firmware \
	-Druntime_dir=/run \
	-Dsession_tracking_consolekit=false \
	-Dsession_tracking=systemd \
	-Dpolkit=true \
	-Dmodify_system=true \
	-Dselinux=false \
	-Dconfig_wifi_backend_default=wpa_supplicant \
	-Dlibaudit=no \
	-Dwext=false \
	-Dwifi=true \
	-Dppp=true \
	-Dmodem_manager=true \
	-Dconcheck=true \
	-Dnmtui=true \
	-Dbluez5_dun=true \
	-Difupdown=true \
	-Dnetconfig=no \
	-Dconfig_dhcp_default=internal \
	-Dqt=false
