#!/bin/sh -eux

ub_compile \
    --enable-gles2=yes \
    --enable-cairo=yes \
    --enable-cogl-pango=yes \
    --enable-gdk-pixbuf=yes \
    --enable-glx=yes \
    --enable-introspection=yes \
    --enable-wayland-egl-platform \
    --enable-wayland-egl-server \
    --enable-xlib-egl-platform
