#!/bin/sh -eux

cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DLIBS_ENTRY_PATH=/usr/lib/q4wine \
    -DWITH_SYSTEM_SINGLEAPP=OFF \
    -DWITH_ICOUTILS=ON \
    -DUSE_GZIP=ON \
    -DRELEASE=ON .
