#!/bin/sh -eux

# cd lang/python/hu/LC_MESSAGES
# rm python.mo
# msgfmt -o python.mo python.po
# cd -
ub_compile \
	-DCMAKE_BUILD_TYPE=Debug \
	-DCMAKE_INSTALL_BINDIR=/usr/sbin \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib
