#!/bin/sh -eux

git clone https://github.com/google/googletest third_party/googletest
git clone https://github.com/google/highway third_party/highway

ub_compile \
    -DBUILD_TESTING=OFF \
    -DJPEGXL_ENABLE_BENCHMARK='false' \
    -DJPEGXL_ENABLE_EXAMPLES='false' \
    -DJPEGXL_ENABLE_FUZZERS='false' \
    -DJPEGXL_ENABLE_VIEWERS='false' \
    -DJPEGXL_ENABLE_SKCMS='false' \
    -DJPEGXL_ENABLE_SJPEG='false' \
    -DJPEGXL_ENABLE_PLUGINS='true' \
    -DJPEGXL_ENABLE_PLUGIN_GIMP210='false' \
    -DJPEGXL_FORCE_SYSTEM_GTEST='false' \
    -DJPEGXL_FORCE_SYSTEM_HWY='false'
