#!/bin/sh -eux

git clone -b lts_2023_08_02 https://github.com/abseil/abseil-cpp.git third_party/abseil-cpp

cp python/dist/setup.py python/setup.py

ub_compile \
    -Dprotobuf_BUILD_TESTS=OFF \
    -DBUILD_SHARED_LIBS=ON

cd python
export PROTOC=../build/protoc
python3 setup.py build
