#!/bin/sh -eux

cd build
ub_install INSTALL_ROOT="$UB_INSTALLDIR"

rm -r "$UB_INSTALLDIR"/usr/lib/python*/site-packages/PyQt5/uic/port_v2

mv "$UB_INSTALLDIR"/bin/* "$UB_INSTALLDIR"/usr/bin/
rm -rf "$UB_INSTALLDIR"/bin
