#!/bin/sh -eux

git clone https://github.com/zherczeg/sljit.git deps/sljit
cd deps/sljit
git checkout 8481dde
cd -

./autogen.sh
ub_configure \
	--enable-pcre2-16 \
	--enable-pcre2-32 \
	--enable-jit \
	--enable-pcre2grep-libz \
	--enable-pcre2grep-libbz2 \
	--enable-pcre2test-libreadline
ub_make
