#!/bin/sh -eux

# vulkan: requires glslang

rm -f subprojects/gtk-doc.wrap

ub_compile \
    -Dx11-backend=true \
	-Dwayland-backend=true \
	-Dbroadway-backend=false \
	-Dvulkan=disabled \
	-Dmedia-ffmpeg=disabled \
	-Dmedia-gstreamer=disabled \
	-Dgtk_doc=false \
	-Dman-pages=false \
	-Ddemos=true \
	-Dintrospection=enabled \
	-Dbuild-examples=false \
	-Dbuild-tests=false \
	-Dbuild-testsuite=false
