#!/bin/sh -eux

# vulkan: requires glslang

rm -Rf subprojects

ub_compile \
    -Dx11-backend=true \
	-Dwayland-backend=true \
	-Dbroadway-backend=false \
	-Dvulkan=disabled \
	-Dmedia-gstreamer=disabled \
	-Ddocumentation=false \
	-Dman-pages=false \
	-Dintrospection=enabled \
	-Dbuild-demos=false \
	-Dbuild-examples=false \
	-Dbuild-tests=false \
	-Dbuild-testsuite=false
