diff -Naur a/Makefile b/Makefile
--- a/Makefile	2024-10-12 13:32:46.000000000 +0200
+++ b/Makefile	2024-10-17 21:41:18.706402008 +0200
@@ -13,10 +13,10 @@
 PKG_CONFIG ?= pkg-config
 
 CC       ?= gcc
-CFLAGS   ?= -g -O3 -Wall
+CFLAGS   ?= -g -O2 -Wall
 
 CXX      ?= g++
-CXXFLAGS ?= -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses
+CXXFLAGS ?= -g -O2 -Wall -Werror=overloaded-virtual -Wno-parentheses
 CXXFLAGS += $(CPPFLAGS)
 
 CDEFINES  = -D_GNU_SOURCE
@@ -40,12 +40,12 @@
 endif
 
 DESTDIR   ?=
-VIDEODIR  ?= /srv/vdr/video
-CONFDIR   ?= /var/lib/vdr
+VIDEODIR  ?= /var/vdr/video
+CONFDIR   ?= /etc/vdr
 ARGSDIR   ?= /etc/vdr/conf.d
 CACHEDIR  ?= /var/cache/vdr
 
-PREFIX    ?= /usr/local
+PREFIX    ?= /usr
 VDRROOT   ?= $(PREFIX)
 BINDIR    ?= $(VDRROOT)/bin
 INCDIR    ?= $(VDRROOT)/include
