#!/bin/sh -eux

ub_compile \
    -Dloaders=glycin-image-rs,glycin-jpeg2000,glycin-jxl,glycin-raw,glycin-svg \
	-Dglycin-thumbnailer=true \
	-Dintrospection=true \
	-Dvapi=true \
	-Dtest_skip_install=true
