#!/bin/sh -eux

python -m installer -d ${UB_INSTALLDIR} dist/*.whl
make -C contrib/chg DESTDIR=${UB_INSTALLDIR} PREFIX=/usr install

install -Dm755 contrib/hg-ssh ${UB_INSTALLDIR}/usr/bin
install -Dm755 contrib/hgk ${UB_INSTALLDIR}/usr/bin
