#!/bin/sh -eux

export CPPFLAGS="-I/usr/include/mariadb"
# NOCONFIGURE=1 ./autogen.sh
ub_compile \
	--enable-srp \
	--enable-srp-setpass \
	--disable-krb4 \
	--with-dblib=berkeley \
	--enable-sql \
	--without-pgsql \
	--without-sqlite \
	--with-ldap \
	--enable-ldapdb \
	--with-saslauthd=/var/run/saslauthd
