#!/bin/bash -eux

make DESTDIR=${UB_INSTALLDIR} FIRMWAREDIR=/usr/lib/firmware install
make DESTDIR=${UB_INSTALLDIR} FIRMWAREDIR=/usr/lib/firmware dedup

rm -Rf ${UB_INSTALLDIR}/usr/lib/firmware/.git

rm -Rf ${UB_INSTALLDIR}/usr/lib/firmware/{Makefile,configure,README*,*.txt,*.py}

# üres könyvtárak törlése
find ${UB_INSTALLDIR} -type d -empty -delete
