#!/bin/sh -eux

# Remove all exe files to ensure we are not shipping prebuilt binaries
# note that those are only used to create Microsoft Windows installers
# and that functionality is broken on Linux anyway
find -name '*.exe' -print -delete

# Remove bundled libraries to ensure that we're using the system copy.
rm -r Modules/expat

ub_configure \
	--with-system-expat \
	--with-tzpath=/usr/share/zoneinfo \
	--enable-optimizations \
	--enable-loadable-sqlite-extensions \
	--without-ensurepip

ub_make
