#!/bin/sh -eux

# https://github.com/KhronosGroup/glslang/blob/master/known_good.json
git clone https://github.com/KhronosGroup/SPIRV-Tools.git External/spirv-tools
cd External/spirv-tools
git checkout ada1771a9f7a125573aa94fe551fdc44b45769bd
cd ../../

git clone https://github.com/KhronosGroup/SPIRV-Headers External/spirv-tools/external/spirv-headers
cd External/spirv-tools/external/spirv-headers
git checkout ddd2c099be25e3fec7cdc14106c17aca99512082
cd -

ub_compile \
	-DBUILD_SHARED_LIBS=OFF \
	-DENABLE_CTEST=OFF
