#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/lib/master-pdf-editor-5
mv masterpdfeditor5.desktop ${UB_INSTALLDIR}/usr/share/applications/
cp -r * ${UB_INSTALLDIR}/usr/lib/master-pdf-editor-5/

# patchelf
find "${UB_INSTALLDIR}"/usr/lib -type f -exec patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 &> /dev/null {} \;
