#!/bin/sh -eux

mkdir -p ${UB_INSTALLDIR}/usr/lib/master-pdf-editor-5
mv usr/share/* ${UB_INSTALLDIR}/usr/share/
mv masterpdfeditor5 ${UB_INSTALLDIR}/usr/bin/masterpdfeditor5
mv masterpdfeditor5.png ${UB_INSTALLDIR}/usr/share/pixmaps/masterpdfeditor5.png
cp -r * ${UB_INSTALLDIR}/usr/lib/master-pdf-editor-5/
rm -Rf ${UB_INSTALLDIR}/usr/lib/master-pdf-editor-5/usr

# patchelf
find "${UB_INSTALLDIR}"/usr/lib -type f -exec patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 &> /dev/null {} \;
