#!/bin/sh -eux

ub_install

mkdir -p "$UB_INSTALLDIR"/usr/share/dict
ln -sf /usr/share/cracklib/cracklib-small "$UB_INSTALLDIR"/usr/share/dict/cracklib-small

export LD_LIBRARY_PATH="$UB_INSTALLDIR/usr/lib:/usr/lib"
"$UB_INSTALLDIR"/usr/sbin/cracklib-format dicts/cracklib-small | "$UB_INSTALLDIR"/usr/sbin/cracklib-packer "$UB_INSTALLDIR"/usr/share/cracklib/pw_dict
