#!/bin/sh -eux

ub_install

mv "$UB_INSTALLDIR"/usr/lib/{perl5/"$UB_VERSION"/*/CORE/libperl.so,}

ln -sf perl"$UB_VERSION" "$UB_INSTALLDIR"/usr/bin/perl
ln -sf perl"$UB_VERSION" "$UB_INSTALLDIR"/usr/bin/perl5

# Fix up xsubpp
ub_replace "^#!./miniperl" "#!/usr/bin/perl" "$UB_INSTALLDIR"/usr/bin/xsubpp
