#!/bin/sh -eux

# git submodule init
# git submodule update

git clone https://gitlab.gnome.org/GNOME/libglnx.git
git clone https://github.com/mendsley/bsdiff.git
git clone https://github.com/containers/composefs.git

NOCONFIGURE=1 ./autogen.sh
ub_compile \
	--with-curl \
	--without-soup \
	--without-composefs
