#!/bin/sh -eux

mv dist/*.whl installer.zip
pythonver=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
sitedir=${UB_INSTALLDIR}/usr/lib/python${pythonver}/site-packages
mkdir -p $sitedir
unzip installer -d $sitedir/
