#!/bin/sh -eux

export CXXFLAGS=`pkg-config --cflags libopenjp2`
export LDFLAGS=`pkg-config --libs libopenjp2`
ub_compile \
	-DENABLE_UNSTABLE_API_ABI_HEADERS=ON \
	-DENABLE_QT5=OFF \
	-DBUILD_QT5_TESTS=OFF
