#!/bin/sh -eux

# vulkan-overlay-layer: https://github.com/KhronosGroup/glslang

ub_compile \
	-Dplatforms=x11,wayland \
	-Ddri3=enabled \
	-Dgles1=disabled \
	-Dgles2=enabled \
	-Dgbm=enabled \
	-Dglx=dri \
	-Degl=enabled \
	-Dglvnd=true \
	-Dllvm=enabled \
	-Dlibunwind=enabled \
	-Dlmsensors=enabled \
	-Dtools=all \
	-Db_ndebug=true \
	-Db_lto=true \
	-Dgallium-drivers=auto \
	-Dvideo-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc
