#!/bin/sh -eux

# static lib kell, ezért nem az ub_compile-t használjuk

meson setup build \
    --prefix="/usr"             \
	--sysconfdir="/etc"         \
	--localstatedir="/var"      \
	--mandir="/usr/share/man"   \
	--infodir="/usr/share/info" \
	--backend=ninja		        \
	--buildtype=release         \
	--default-library=static

ub_make
