#!/bin/sh -eux

cp -a modules/pam_envfeed/Makefile{,.in}

CFLAGS="-fPIC -O2" \
ub_compile \
	--sbindir=/usr/sbin \
	--libdir=/usr/lib \
	--disable-doc \
	--disable-nis \
	--disable-Werror

ub_make -C modules/pam_envfeed
